### ISSUE TITLE
License mismatch

### ISSUE THREAD

**Issue by macrologist** [plandes/cl-jsonl#1]
Free software is dead and all but GTWIWTG is released under the GPL 3.0 license. CL-JSONL is currently released under MIT, in violation of the GPL 3.0 

Just wanted to raise this issue in case you're using CL-JSONL commercially and it ends up mattering at some point.

Also, it's cool that you're using GTWIWTG! I'm the author and I don't use it for anything.

**Comment by plandes** [comment]
@macrologist It's funny because I don't use `cl-jsonl` for anything but I think its cool you're using it (or hope more than at least one person is).  It's really too bad Python became the primary language for AI rather than CL still being used for it (Grammarly is a notable exception).  Anyways, thanks for spotting this before I was picked up by the GPL licensee police (or Stallman).  It is [now in sync](https://github.com/plandes/cl-jsonl/commit/ca813e08646061dd31105d04b5d001ee674a8429).

In all seriousness GTWIWTG is a great library. Thanks for writing it.
